eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
  instance:
    prefer-ip-address: true #使用ip注册到eureka服务列表
server:
  port: 3003
spring:
  application:
    name: plat-service